<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.hp.demo.client.notifications.NotificationsEventFactoryTest" time="0" tests="2" errors="0" skipped="0" failures="1">
  <testcase name="testNullListener" classname="com.hp.demo.client.notifications.NotificationsEventFactoryTest" time="0">
    <failure message="Continuously failing" type="java.lang.AssertionError">
      java.lang.AssertionError: Continuously
      failing
      at org.junit.Assert.fail(Assert.java:88)
      at
      com.hp.demo.client.notifications.NotificationsEventFactoryTest.testNullListener(NotificationsEventFactoryTest.java:34)
    </failure>
  </testcase>
  <testcase name="testCreateModule" classname="com.hp.demo.client.notifications.NotificationsEventFactoryTest" time="0"/>
</testsuite>